channels:
  - conda-forge
  - bioconda
  - plotly
  - nvidia
dependencies:
  - conda-forge::python==3.10.*
  - conda-forge::pip
  - nvidia::cudatoolkit==11.6.*
  - bioconda::mmseqs2
  - bioconda::blast
  - bioconda::clustalw
  - plotly::plotly
  - pip:
      - accelerate
      - biopython
      - datasets
      - deepspeed
      - diffusers
      - pytest
      - torch
      - logomaker
      - numpy
      - transformers
      - sentencepiece
      - ipython

