channels:
  - conda-forge
  - bioconda
  - plotly
  - pytorch
  - nvidia
dependencies:
  - conda-forge::python==3.9.*
  - conda-forge::pip
  - conda-forge::cudatoolkit==11.6.*
  - bioconda::mmseqs2
  - bioconda::blast
  - bioconda::clustalw
  - plotly::plotly
  - pytorch::pytorch>=1.12.*
  - pytorch::pytorch-cuda=11.6
  - pip:
      - accelerate
      - biopython
      - datasets
      - deepspeed
      - diffusers
      - pytest
      - logomaker
      - numpy
      - transformers
      - sentencepiece
      - ipython

